[package]
org = "ballerinax"
name = "ObservationAPI"
version = "1.0.2"
export = ["ObservationAPI"]
distribution = "2201.5.0"
authors = ["Ballerina"]
keywords = ["Healthcare","FHIR","Observation","r4","international"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.templates"

[build-options]
observabilityIncluded = true
